.TH "rep_ingredientes" 3 "Domingo, 1 de Diciembre de 2019" "Version 0.1" "Práctica 3 - Estructura de Datos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rep_ingredientes \- Rep del TDA \fBIngredientes\fP 

.SH "Invariante de la representación"
.PP
El invariante es \fIVector_Dinamico\fP de ingredientes llamado datos válido
.SH "Función de abstracción"
.PP
Un objeto válido \fIrep\fP del TDA \fBIngredientes\fP representa al valor
.PP
{datos} 
