.TH "rep_ingrediente" 3 "Domingo, 1 de Diciembre de 2019" "Version 0.1" "Práctica 3 - Estructura de Datos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rep_ingrediente \- Rep del TDA \fBIngrediente\fP 

.SH "Invariante de la representación"
.PP
El invariante es \fI0\fP <= rep\&.hidratos <= 100 \fI0\fP <= rep\&.proteinas <= 100 \fI0\fP <= rep\&.grasas <= 100 \fI0\fP <= rep\&.fibras <= 100
.SH "Función de abstracción"
.PP
Un objeto válido \fIrep\fP del TDA \fBIngrediente\fP representa al valor
.PP
{Nombre, Calorias, Hidratos, Proteinas, Grasas, Fibras, Tipo} 
