.TH "rep_vector__dinamico" 3 "Domingo, 27 de Octubre de 2019" "Version 0.1" "Práctica 2 - Estructura de Datos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rep_vector__dinamico \- Rep del TDA \fBVector_Dinamico\fP 

.SH "Invariante de la representación"
.PP
El invariante es \fIpuntero\fP *datos válido
.SH "Función de abstracción"
.PP
Un objeto válido \fIrep\fP del TDA \fBVector_Dinamico\fP representa al valor
.PP
{datos, numElementos, reservados} 
