.TH "include/vector_dinamico.h" 3 "Domingo, 27 de Octubre de 2019" "Version 0.1" "Práctica 2 - Estructura de Datos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/vector_dinamico.h \- Fichero cabecera del TDA \fBVector_Dinamico\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'vector_dinamico\&.tpp'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBVector_Dinamico< T >\fP"
.br
.RI "T\&.D\&.A \fBVector_Dinamico\fP\&. "
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA \fBVector_Dinamico\fP\&. 


.PP
Definición en el archivo \fBvector_dinamico\&.h\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Práctica 2 - Estructura de Datos del código fuente\&.
