.TH "Acciones::iterator" 3 "Domingo, 29 de Diciembre de 2019" "Version 0.1" "Práctica 3 - Estructura de Datos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Acciones::iterator \- Clase para iterar sobre las acciones\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <acciones\&.h>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBiterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "pair< const string, unsigned char > & \fBoperator*\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBiterator\fP &i)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBiterator\fP &i)"
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator=\fP (const \fBiterator\fP &i)"
.br
.in -1c
.SS "Amigas"

.in +1c
.ti -1c
.RI "class \fBAcciones\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Clase para iterar sobre las acciones\&. 
.PP
Definición en la línea 68 del archivo acciones\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Práctica 3 - Estructura de Datos del código fuente\&.
