.TH "include/acciones.h" 3 "Domingo, 29 de Diciembre de 2019" "Version 0.1" "Práctica 3 - Estructura de Datos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/acciones.h \- Fichero cabecera del TDA \fBAcciones\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <map>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBAcciones\fP"
.br
.ti -1c
.RI "class \fBAcciones::iterator\fP"
.br
.RI "Clase para iterar sobre las acciones\&. "
.ti -1c
.RI "class \fBAcciones::const_iterator\fP"
.br
.RI "Clase para iterar sobre las acciones\&. "
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA \fBAcciones\fP\&. 


.PP
Definición en el archivo \fBacciones\&.h\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Práctica 3 - Estructura de Datos del código fuente\&.
