.TH "Ingredientes::iterator" 3 "Domingo, 1 de Diciembre de 2019" "Version 0.1" "Práctica 3 - Estructura de Datos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ingredientes::iterator \- Clase para iterar sobre los ingredientes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ingredientes\&.h>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBiterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "\fBIngrediente\fP & \fBoperator*\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBiterator\fP &i)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBiterator\fP &i)"
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator=\fP (const \fBiterator\fP &i)"
.br
.in -1c
.SS "Amigas"

.in +1c
.ti -1c
.RI "class \fBIngredientes\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Clase para iterar sobre los ingredientes\&. 
.PP
Definición en la línea 210 del archivo ingredientes\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Práctica 3 - Estructura de Datos del código fuente\&.
