.TH "include/ingredientes.h" 3 "Domingo, 29 de Diciembre de 2019" "Version 0.1" "Práctica 3 - Estructura de Datos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ingredientes.h \- Fichero cabecera del TDA \fBIngredientes\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'ingrediente\&.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBIngredientes\fP"
.br
.RI "T\&.D\&.A \fBIngredientes\fP\&. "
.ti -1c
.RI "class \fBIngredientes::iterator\fP"
.br
.RI "Clase para iterar sobre los ingredientes\&. "
.ti -1c
.RI "class \fBIngredientes::const_iterator\fP"
.br
.RI "Clase para iterar sobre los ingredientes (modo const) "
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA \fBIngredientes\fP\&. 


.PP
Definición en el archivo \fBingredientes\&.h\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Práctica 3 - Estructura de Datos del código fuente\&.
