.TH "include/recetas.h" 3 "Domingo, 29 de Diciembre de 2019" "Version 0.1" "Práctica 3 - Estructura de Datos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/recetas.h \- Fichero cabecera del TDA \fBRecetas\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'receta\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <map>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBRecetas\fP"
.br
.RI "T\&.D\&.A \fBRecetas\fP\&. "
.ti -1c
.RI "class \fBRecetas::iterator\fP"
.br
.RI "Clase para iterar sobre los ingredientes\&. "
.ti -1c
.RI "class \fBRecetas::const_iterator\fP"
.br
.RI "Clase para iterar sobre los ingredientes (modo const) "
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA \fBRecetas\fP\&. 


.PP
Definición en el archivo \fBrecetas\&.h\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Práctica 3 - Estructura de Datos del código fuente\&.
