.TH "include/receta.h" 3 "Domingo, 29 de Diciembre de 2019" "Version 0.1" "Práctica 3 - Estructura de Datos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/receta.h \- Fichero cabecera del TDA \fBReceta\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <list>\fP
.br
\fC#include 'ingredientes\&.h'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBReceta\fP"
.br
.RI "T\&.D\&.A \fBReceta\fP\&. "
.ti -1c
.RI "class \fBReceta::iterator\fP"
.br
.RI "Clase para iterar sobre los ingredientes\&. "
.ti -1c
.RI "class \fBReceta::const_iterator\fP"
.br
.RI "Clase para iterar sobre los ingredientes (modo const) "
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA \fBReceta\fP\&. 


.PP
Definición en el archivo \fBreceta\&.h\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Práctica 3 - Estructura de Datos del código fuente\&.
