.TH "rep_receta" 3 "Domingo, 1 de Diciembre de 2019" "Version 0.1" "Práctica 3 - Estructura de Datos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rep_receta \- Rep del TDA \fBReceta\fP 

.SH "Invariante de la representación"
.PP
El invariante es \fIcode\fP, plato, nombre, ings, calorias, hc, grasas, proteinas,fibra que representan la invariante de \fBReceta\fP
.SH "Función de abstracción"
.PP
Un objeto válido \fIrep\fP del TDA \fBReceta\fP representa al valor
.PP
{code, plato, nombre, ings, calorias, hc, grasas, proteinas,fibra}
.SH "Invariante de la representación"
.PP
El invariante es \fIdatos\fP, un vector dinamico
.SH "Función de abstracción"
.PP
Un objeto válido \fIrep\fP del TDA \fBRecetas\fP representa al valor
.PP
{datos} 
